version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AppSettings__Blockchain__EthereumRpcUrl=https://mainnet.infura.io/v3/${INFURA_API_KEY}
      - AppSettings__Blockchain__EtherscanApiKey=${ETHERSCAN_API_KEY}
      - AppSettings__Cache__UseRedisCache=true
      - AppSettings__Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - defi-network

  frontend:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - defi-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - defi-network

networks:
  defi-network:
    driver: bridge

volumes:
  redis-data: 